apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  name: mongodb-eks
  namespace: mongodb-eks
spec:
  crVersion: 1.22.0
  image: percona/percona-server-mongodb:8.0.19-7
  imagePullPolicy: Always
  # unsafeFlags:
  #   replsetSize: true
  replsets:
    - name: main
      size: {{ .Values.replsets.rs0.size }}
      serviceAccountName: {{ .Values.replsets.rs0.serviceAccountName }}
    #   serviceAccountName: percona-backup-sa
      volumeSpec:
        persistentVolumeClaim:
          storageClassName: {{ .Values.replsets.rs0.volumeSpec.pvc.storageClassName }}
          accessModes:
            - "ReadWriteOnce"
          resources:
            requests:
              storage: {{ .Values.replsets.rs0.volumeSpec.pvc.resources.requests.storage }}
  backup:
    enabled: {{ .Values.backup.enabled }}
    image: percona/percona-backup-mongodb:2.12.0
    storages:
      s3-percona-test-05-03-2026:
        type: s3
        s3:
          bucket: {{ .Values.backup.storages.s3-percona-test-05-03-2026.s3.bucket }}
          region: {{ .Values.backup.storages.s3-percona-test-05-03-2026.s3.region }}
    tasks:
      - name: {{ .Values.backup.tasks[0].name }}
        enabled: {{ .Values.backup.tasks[0].enabled }}
        schedule: {{ .Values.backup.tasks[0].schedule }}
        retention:
          count: {{ .Values.backup.tasks[0].retention.count }}
          type: {{ .Values.backup.tasks[0].retention.type }}
          deleteFromStorage: {{ .Values.backup.tasks[0].retention.deleteFromStorage }}
        type: {{ .Values.backup.tasks[0].type }}
        storageName: {{ .Values.backup.tasks[0].storageName }}
