apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-eks
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: mongodb-eks
  sources:

    - repoURL: "https://github.com/YURIIOZHHO/argocd-test.git"
      targetRevision: main
      ref: values

    - chart: psmdb-operator-crds
      repoURL: https://percona.github.io/percona-helm-charts/
      targetRevision: 1.22.0

    - chart: psmdb-operator
      repoURL: https://percona.github.io/percona-helm-charts/
      targetRevision: 1.22.0

    - chart: psmdb-db
      repoURL: https://percona.github.io/percona-helm-charts/
      targetRevision: 1.22.0
      helm:
         releaseName: psmdb-db
         valueFiles:
          - $values/charts/mongodb-eks/dev/values_dev.yaml

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      # - SkipDryRunOnMissingResource=true
      - ServerSideApply=true