apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mongodb-eks
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: mongodb-eks
  sources:
    - chart: psmdb-operator-crds
      repoURL: https://percona.github.io/percona-helm-charts/
      targetRevision: 1.22.0
      # helm:
      #   releaseName: psmdb-operator
      #   valueFiles:
      #     - $values/charts/mongodb-eks/dev/values_dev.yaml
      values: |
        replsets:
          size: 3

    - chart: psmdb-operator
      repoURL: https://percona.github.io/percona-helm-charts/
      targetRevision: 1.22.0
      # helm:
      #   releaseName: psmdb-operator
      #   valueFiles:
      #     - $values/charts/mongodb-eks/dev/values_dev.yaml
      values: |
        replsets:
          size: 3


    - repoURL: "https://github.com/YURIIOZHHO/argocd-test.git"
      path: "charts/mongodb-eks/dev"
      targetRevision: main
      values: |
        replsets:
          size: 3

  project: default
  syncPolicy:
    automated:
      prune   : true
      selfHeal: true
    syncOptions:
      # - SkipDryRunOnMissingResource=true
      - ServerSideApply=true